version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    links:
      - "db:mysql.host"
      - "redis:redis.host"
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL
      - EMAIL_PORT
      - EMAIL_USERNAME
      - EMAIL_PASSWORD
    depends_on:
      - db
      - redis
  db:
    platform: linux/x86_64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=your_mysql_root_password
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    environment:
      - REDIS_URL
